# Generated by Django 3.2.10 on 2021-12-31 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(default='defualt.png', upload_to='item_pics'),
        ),
    ]
